# Application Name
spring.application.name=hospitalManagement

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital
spring.datasource.username=postgres
spring.datasource.password=root

server.servlet.context-path=/api/v1


# Hibernate JPA Configuration
# For production, switch to: validate or none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


#spring.jpa.defer-datasource-initialization=true
#spring.sql.inti.mode=always
#spring.sql.init.data-locations=classpath:data.sql


jwt.secretKey=buh485dbciwi9erfre84h9bcjdcn9edfvf28dsafasd3fen6rvdssg8rg4f

#spring.seccurity.oauth2.client.registration.google.client-id=
#spring.seccurity.oauth2.client.registration.google.client-secret=