# Application Name
spring.application.name=hospitalManagement

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital
spring.datasource.username=postgres
spring.datasource.password=root

server.servlet.context-path=/api/v1

# Hibernate JPA Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

jwt.secretKey=buh485dbciwi9erfre84h9bcjdcn9edfvf28dsafasd3fen6rvdssg8rg4f